---
########
# Argmap environment data - DEFAULTS
# Copy this to config/environment-argmap.yaml and customise as you wish
#   So this file IS considered part of the public API for this app and changing variable names etc will be considered BREAKING.
# For use in scripts, layouts and lua code.
# Copyright 2022 Michael Hayes
# SPDX - License - Identifier: MIT
########

# Use ${variable} for referencing other yaml variables, since this is compatible with both bash and pandoc templates.

# Paths

## web server
DIR_PUBLIC: public
PATH_DIR_PUBLIC: ${PATH_DIR_MAPJS_ROOT}/${DIR_PUBLIC}
PORT_DEBUG: 9221
PORT_DEV_SERVER: 9001

## lua
PATH_DIR_ARGMAP_LUA: ${PATH_DIR_ARGMAP_ROOT}/src/lua
LUA_CPATH: ${PATH_DIR_ARGMAP_ROOT}/lua_modules/lib/lua/5.3/?.so;
LUA_PATH: ${PATH_DIR_ARGMAP_ROOT}/src/lua/?.lua;${PATH_DIR_ARGMAP_ROOT}/lua_modules/share/lua/5.3/?.lua;${PATH_DIR_ARGMAP_ROOT}/lua_modules/share/lua/5.3/?/init.lua;

## mapjs
DIR_MAPJS: mapjs
PATH_DIR_MAPJS_ROOT: ${PATH_DIR_ARGMAP_ROOT}/${DIR_MAPJS}

## pandoc
PATH_FILE_PANDOC_FILTER_LUA_ARGMAP: ${PATH_DIR_ARGMAP_LUA}/pandoc-argmap.lua
PANDOC_DATA_DIR: ${CONDA_PREFIX}/share/pandoc

## External to project
DIR_PROJECTS: /home/s6mike/git_projects
PATH_MISC_DEV: ${DIR_PROJECTS}/misc
PATH_CHROME_PROFILE_DEBUG: ${PATH_MISC_DEV}/chrome-debug-argmap
PATH_TEST_LOG: "${PATH_MISC_DEV}/tests_output.txt"
DEFAULT_DIFF_FILENAME: ${DIR_PROJECTS}/mapjs-git-bisect/diffs/all_mapjs_fixes_latest_modified.diff

## GDrive
GDRIVE_FOLDER_ID_MAPJS_DEFAULT: 1cSnE4jv5f1InNVgYg354xRwVPY6CvD0x # Default mapjs upload folder
GDRIVE_FILE_ID_MAPJS_DEFAULT: 138E5WcQos2NNxN4_pCuw83DnZnqKO36Z # Default mapjs upload gdrive id

...
